<script>

    export default {
        name: 'StartMenu',
        data() {
            return {

            }
        },
        created() {
        },
        methods: {
            setBackground(x) {

                const text = document.getElementById('presentation');
                text.style.backgroundColor = "rgba(0, 0, 0, 0.8)";
            
                const contentBackground = document.getElementById('content');

                if (x === 'fantasy') {
                    // console.log('fantasy');
                    contentBackground.style.backgroundImage = "url('https://wallpapers-fenix.eu/full/210222/030317153.jpg')";
                } else if (x === 'horror') {
                    // console.log('ciao');
                    contentBackground.style.backgroundImage = "url('https://images.unsplash.com/photo-1606639421367-97fba5c3833a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8NXx8fGVufDB8fHx8fA%3D%3D&w=1000&q=80')";
                } else if (x === 'supereroi') {
                    contentBackground.style.backgroundImage = "url('https://cdn.vox-cdn.com/thumbor/4OG-1TdCrPpLFW1Tte0IEjIriSw=/0x0:2040x1360/1200x675/filters:focal(857x517:1183x843)/cdn.vox-cdn.com/uploads/chorus_image/image/66663243/jbareham_200330_0988_comic_stores.0.jpg')";
                }
            },

            clearBackground() {
                const contentBackground = document.getElementById('content');

                contentBackground.style.backgroundImage = "url('https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/A_black_image.jpg/640px-A_black_image.jpg')";
            }

        }
    }

</script>

<template>

    <div id="content" class="transition-background">

        <div class="container">

            <div id="presentation">
                <h1 class="text-center">
                    Welcome adventurer
                </h1>

                <p>
                    This will be a story generated by OpenAI. You will be presented with an event and each time you will have three choices. Be careful because one choice will lead you to death.
                </p>

                <p>
                    Now choose the setting of your story:
                </p>

            </div>
            
            <div class="menu-options">

                <router-link :to="{ name: 'playground', params: { genre: 'fantasy' } }" class="menu-option left" >
                    fantasy
                </router-link>

                <router-link :to="{ name: 'playground', params: { genre: 'horror' } }" class="menu-option center" >
                    horror
                </router-link>

                <router-link :to="{ name: 'playground', params: { genre: 'supereroi' } }" class="menu-option right"> <!-- @mouseenter="setBackground('supereroi')" @mouseleave="clearBackground()" -->
                    superheroes
                </router-link>

            </div>
        </div>

    </div>
  
  </template>
  
<style lang="scss" scoped>
@use '../style/main.scss';

    #content {
        background-color: black;
        color: white;

        min-height: calc(100vh - 60px);
        padding: 20px 0;
    
        background-repeat: no-repeat;
        background-size: cover;
        transition: background-image 1s ease-in-out;
    }

    .container {

        #presentation {
            border-radius: 10px;
            padding: 10px 15px;
            margin: 10px 0 30px;
            
            h1 {
                color: green;
                text-transform: uppercase;
                font-weight: bold;
                letter-spacing: 3px;
            }

            p {
                text-align: center;
                margin: 10px 0;
                font-size: 25px;
            }
        }

        .menu-options {

            .menu-option {
                margin: auto;
                margin-bottom: 10px;

                border: 2px solid white;
                border-radius: 0%;
                width: 200px;
                height: 200px;
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;

                text-decoration: none;
                color: inherit;
                text-transform: uppercase;
            }

        }

    }

    @media screen and (min-width: 768px) {
        .menu-options {
            margin: 30px auto 0;
            width: 95%;
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;

            .menu-option {
                margin-bottom: 0;
                filter: blur(1.3px);
                transition: all 0.8s;

                &:hover {
                    filter: blur(0);
                    // background-color: rgba(0, 0, 0, 0.8);
                    transform: scale(1.2);
                    border-radius: 50%;
                    // background-image: url("https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHd4YTB2cmZtd3Zob2NqOWUyZDQ1eGxlZ25rbG0xY3JmMDM1dGx3YyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tA4R6biK5nlBVXeR7w/giphy.gif");
                    background-size: cover;
                    border-color: transparent;
                    border-width: 3px;
                    animation-duration: 2s;
                    animation-iteration-count:infinite;
                    animation-timing-function: ease-in-out;
                }
                &:hover.left {
                    animation-name: anime-left;
                }
                &:hover.center{
                    animation-name: anime-center;
                }
                &:hover.right {
                    animation-name: anime-right;
                }
                // animazione sinistra
                @keyframes anime-left {
                    25% {
                        border-top-color: white;
                        border-top-width: 2px;
                    }
                    50% {
                        border-right-color: white;
                        border-right-width: 4px;
                    }
                   75% {
                        border-bottom-color: white;
                        border-bottom-width: 6px;
                    }
                   100% {
                        border-left-color: white;
                        border-left-width: 8px;
                   }
                }
                // animazione centro
                @keyframes anime-center {
                    25% {
                        border-left-color: white;
                        border-left-width: 2px;
                    }
                    50% {
                        border-bottom-color: white;
                        border-bottom-width: 4px;
                    }
                   75% {
                        border-right-color: white;
                        border-right-width: 6px;
                    }
                   100% {
                        border-top-color: white;
                        border-top-width: 8px;
                   }
                }
                // animazione destra
                @keyframes anime-right {
                    25% {
                        border-top-color: white;
                        border-top-width: 2px;
                    }
                    50% {
                        border-left-color: white;
                        border-left-width: 4px;
                    }
                   75% {
                        border-bottom-color: white;
                        border-bottom-width: 6px;
                    }
                   100% {
                        border-right-color: white;
                        border-right-width: 8px;
                   }
                }

            }
        }

        
    }

    

</style>