<script>

    export default {
        name: 'StartMenu',
        data() {
            return {

            }
        },
        created() {
        },
        methods: {
            setBackground(x) {

                const text = document.getElementById('presentation');
                text.style.backgroundColor = "rgba(0, 0, 0, 0.7)";
            
                const contentBackground = document.getElementById('content');

                if (x === 'fantasy') {
                    // console.log('fantasy');
                    contentBackground.style.backgroundImage = "url('https://wallpapers-fenix.eu/full/210222/030317153.jpg')";
                } else if (x === 'horror') {
                    // console.log('ciao');
                    contentBackground.style.backgroundImage = "url('https://images.unsplash.com/photo-1606639421367-97fba5c3833a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8NXx8fGVufDB8fHx8fA%3D%3D&w=1000&q=80')";
                } else if (x === 'supereroi') {
                    contentBackground.style.backgroundImage = "url('https://cdn.vox-cdn.com/thumbor/4OG-1TdCrPpLFW1Tte0IEjIriSw=/0x0:2040x1360/1200x675/filters:focal(857x517:1183x843)/cdn.vox-cdn.com/uploads/chorus_image/image/66663243/jbareham_200330_0988_comic_stores.0.jpg')";
                }
            },

            clearBackground() {
                const contentBackground = document.getElementById('content');

                contentBackground.style.backgroundImage = "url('https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/A_black_image.jpg/640px-A_black_image.jpg')";
            }

        }
    }

</script>

<template>

    <div id="content" class="transition-background">

        <div class="container">

            <div id="presentation">
                <h1 class="text-center">
                    Welcome adventurer
                </h1>

                <p>
                    This will be a story generated by OpenAI. You will be presented with an event and each time you will have three choices. Be careful because one choice will lead you to death.
                </p>

                <p>
                    Now choose the setting of your story
                </p>

            </div>
            
            <div class="menu-options">

                <router-link :to="{ name: 'playground', params: { genre: 'fantasy' } }" class="menu-option" @mouseenter="setBackground('fantasy')" @mouseleave="clearBackground()">
                    fantasy
                </router-link>

                <router-link :to="{ name: 'playground', params: { genre: 'horror' } }" class="menu-option" @mouseenter="setBackground('horror')" @mouseleave="clearBackground()">
                    horror
                </router-link>

                <router-link :to="{ name: 'playground', params: { genre: 'supereroi' } }" class="menu-option" @mouseenter="setBackground('supereroi')" @mouseleave="clearBackground()">
                    superheroes
                </router-link>

            </div>
        </div>

    </div>
  
  </template>
  
<style lang="scss" scoped>
@use '../style/main.scss';

    #content {
        background-color: black;
        color: white;

        min-height: calc(100vh - 60px);
        padding: 20px 0;
    
        background-repeat: no-repeat;
        background-size: cover;
        transition: background-image 1s ease-in-out;
    }

    .container {

        #presentation {
            
            border-radius: 10px;
            padding: 5px 0;

            h1 {
                color: green;
            }

            p {
                text-align: center;
                margin: 10px 0;
            }
        }

        .menu-options {
            // display: flex;
            // flex-direction: column;
            // align-items: center;

            .menu-option {
                margin: auto;
                margin-bottom: 10px;

                border: 2px solid white;
                width: 150px;
                height: 150px;
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;

                text-decoration: none;
                color: inherit;
                text-transform: uppercase;

                
            }

        }

    }

    @media screen and (min-width: 768px) {
        .menu-options {
            margin: 30px auto 0;
            width: 95%;
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;

            // position: absolute;
            // top: 50%;
            // left: 50%;
            // transform: translate(-50%, -50%);

            .menu-option {
                margin-bottom: 0;
                filter: blur(1.3px);
                    transition: 1.2s all;

                &:hover {
                    // background-color: darkcyan;
                    filter: blur(0);
                    background-color: rgba(0, 0, 0, 0.6);
                }
            }
        }

        
    }

    

</style>